"DOTAAbilities"
{
     "common_attack_good_datadriven"
	{
        // General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"				        "ability_lua"
		"AbilityTextureName"			"spectre_dispersion"
		
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"
		"ScriptFile"					"magic/common_attack_good.lua"	
		
		"MaxLevel"                      "1"

		// myset
		"UnitType"         				"base"
		"AbilityLevel"					"d"
		"IconSrc" "file://{images}/custom_game/ability_button/spectre_dispersion.png"  //选择框图标

		"unitModel"			"shootUnit-XS"
		"hitType" 			"1"   //3直达不触碰,2穿透弹,1触碰爆炸
		"isAOE"             "0"
		"isMisfire"			"1"

		
		"precache"						
		{
			"soundfile"			"soundevents/voscripts/game_sounds_vo_magic.vsndevts"
		}

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1500"   //施法距离
		"AbilityCastPoint"				"0.15"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"0"

		"AbilityCharges"                "3"
        "AbilityChargeRestoreTime"      "3"
		
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"12"






        "AbilitySpecial"
		{
            "01"
			{
				"var_type"			"FIELD_FLOAT"
				"speed"				"550"
			}
            "02"
			{
				"var_type"			"FIELD_FLOAT"
				"max_distance"		"1500"
			}
            "03"
			{
				"var_type"			"FIELD_FLOAT"
				"hit_range"		    "65"
			}
            "04"
			{
				"var_type"			"FIELD_FLOAT"
				"damage"		    "8"
			}


            "06"
			{
				"var_type"			"FIELD_INTEGER"
				"max_charges"		"3"
			}
			"07"
			{
				"var_type"				"FIELD_FLOAT"
				"charge_replenish_time"	"3"
			}
			"12"
			{
				"var_type"					"FIELD_FLOAT"
				"energy"					"10"
			}

			
        }

        

		"OnSpellStart"
		{		
			"RunScript"
			{
				"ScriptFile"		"magic/common_attack_good.lua"
				"Function"			"createShoot"
				"unitModel"			"shootUnit-XS"
				"AbilityLevel"		"d"
				"unitType"          "base"
				"hitType" 			"1"   //3直达不触碰,2穿透弹,1触碰爆炸

				"isMisfire"			"1"
				"particles_hit_dur" "0.7"
                "cp"				 "3"

				"particles_nm"      "particles/yanggongji.vpcf"
				"soundCast" 		"magic_common_attack_good_cast"

				"particles_misfire" "particles/yanggongji_jiluo.vpcf"
				"soundMisfire"		"magic_common_attack_good_mis_fire"
                "particles_miss"    "particles/yanggongji_xiaoshi.vpcf"
				"soundMiss"			"magic_common_attack_good_miss"

                "particles_boom" 	"particles/yanggongji_mingzhong.vpcf"
				"soundBoom"			"magic_common_attack_good_boom"

			}
		}
    }
}