"DOTAAbilities"
{
     "common_attack_bad_datadriven"
	{
        // General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"				        "ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"


		"AbilityTextureName"			"shadow_demon_disruption"
		"MaxLevel"                      "1"
		"UnitType"         				"base"
		"AbilityLevel"					"d"
		"IconSrc" "file://{images}/custom_game/ability_button/shadow_demon_disruption.png"  //选择框图标

		
		"precache"						
		{
			"soundfile"			"soundevents/voscripts/game_sounds_vo_magic.vsndevts"
		}

		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1500"   //施法距离
		"AbilityCastPoint"				"0.15"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"0.3"
		
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"10"


        "AbilitySpecial"
		{
            "01"
			{
				"var_type"			"FIELD_FLOAT"
				"speed"				"450"
			}
            "02"
			{
				"var_type"			"FIELD_FLOAT"
				"max_distance"		"1500"
			}
            "03"
			{
				"var_type"			"FIELD_FLOAT"
				"hit_range"		    "65"
			}
            "04"
			{
				"var_type"			"FIELD_FLOAT"
				"damage"		    "8"
			}


            "06"
			{
				"var_type"			"FIELD_INTEGER"
				"max_charges"		"4"
			}
			"07"
			{
				"var_type"				"FIELD_FLOAT"
				"charge_replenish_time"	"2"
			}
        }

        "OnUpgrade"
		{
			"RunScript"
			{
				"ScriptFile"			"magic/common_attack_bad.lua"
				"Function"				"shootStartCharge"
				"modifierCountName"		"modifier_counter_common_attack_bad_datadriven"
			}
		}

		"OnSpellStart"
		{		
			"RunScript"
			{
				"ScriptFile"		"magic/common_attack_bad.lua"
				"Function"			"createShoot"
				"unitModel"			"shootUnit-S"
				"AbilityLevel"		"d"
				"unitType"          "base"
				"hitType" 			"1"   //3直达不触碰,2穿透弹,1触碰爆炸

				"isMisfire"			"1"
				"particles_hit_dur" "0.7"
                "cp"				 "3"

				"particles_nm"      "particles/yingongji.vpcf"
				"soundCast" 		"magic_common_attack_bad_cast"

				"particles_misfire" "particles/yingongji_jiluo.vpcf"
				"soundMisfire"		"magic_common_attack_bad_mis_fire"
                "particles_miss"    "particles/yingongji_xiaoshi.vpcf"
				"soundMiss"			"magic_common_attack_bad_miss"
				

				
                "particles_boom" 	"particles/yingongji_mingzhong.vpcf"
				"soundBoom"			"magic_common_attack_bad_boom"

                "modifierCountName" "modifier_counter_common_attack_bad_datadriven"
				
			}
		}

		"Modifiers"
		{
            "modifier_counter_common_attack_bad_datadriven"
			{
				"Passive"				"1"
			}

		}
    }
}