"DOTAAbilities"
{
    "frost_blast_pre_datadriven"
	{
    // General
		//-------------------------------------------------------------------------------------------------------------
		"BaseClass"						"ability_datadriven"
		"AbilityBehavior"				"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"			"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"			"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"			"DAMAGE_TYPE_MAGICAL"

		"AbilityTextureName"			"lich_chain_frost"
		"MaxLevel"                      "1"
		"AOERadius"                     "400"
		"UnitType"         				"shui"
		"AbilityLevel"					"a"
		"PreAbility"					"null"
		"StageAbility"					"null"

		"IconSrc" 						"file://{images}/custom_game/ability_button/lich_chain_frost.png"  //选择框图标
		"AbilityShowName" 				"#UIButton4"
		"AbilityDescribe"					"#UIButton4"
		
		"precache"						
		{
			"soundfile"			"soundevents/voscripts/game_sounds_vo_magic.vsndevts"
		}
	
		// Casting
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCastRange"				"1600"   //施法距离
		"AbilityCastPoint"				"0.3"

		// Time		
		//-------------------------------------------------------------------------------------------------------------
		"AbilityCooldown"				"25"
		
		// Cost
		//-------------------------------------------------------------------------------------------------------------
		"AbilityManaCost"				"44"

        "AbilitySpecial"
		{
            "01"
			{
				"var_type"			"FIELD_FLOAT"
				"speed"				"420"
			}
            "04"
            {
                "var_type"			"FIELD_FLOAT"
                "aoe_radius"		"400"
            }
            "06"
			{
				"var_type"			"FIELD_FLOAT"
				"max_distance"		"1600"
			}
            "20"
			{
				"var_type"			"FIELD_FLOAT"
				"hit_range"		    "100"
			}
            "07"
			{
				"var_type"			"FIELD_FLOAT"
				"damage"		    "10"
			}

            "33"
            {
                "var_type"			"FIELD_FLOAT"
                "debuff_duration"	"5"
            }
            "64"
            {
                "var_type"			"FIELD_FLOAT"
                "speed_percent"		"-40"
            }
            "63"
            {
                "var_type"			"FIELD_FLOAT"
                "turn_rate_percent"		"-50"
            }
			"72"
            {
                "var_type"			"FIELD_FLOAT"
                "diffuse_speed"		"250"
            }
			"12"
			{
				"var_type"			"FIELD_FLOAT"
				"energy"			"80"
			}
			
        }

        "OnSpellStart"
		{
			"RunScript"
			{
				"ScriptFile"		"magic/frost_blast.lua"
				"Function"			"createFrostBlast"
				"Target"			"POINT"
				"unitModel"			"shootUnit-L"
				"AbilityLevel"		"a"
				"unitType"          "shui"
				"hitType" 			"1"   //3直达不触碰,2穿透弹,1触碰爆炸
                "isAOE"             "1"
				"particles_nm"      "particles/44bingshuangchongji_shengcheng.vpcf"
				"soundCast"			"magic_frost_blast_cast"
				"particles_hit_dur" "0.7"
				"particles_power" 	"particles/44bingshuangchongji_jiaqiang.vpcf"
				"soundPower"		"magic_water_power_up"
				"particles_weak" 	"particles/44bingshuangchongji_xueruo.vpcf"
				"soundWeak"			"magic_water_power_down"
                "particles_boom" 	"particles/44bingshuangchongji_baozha.vpcf"
				"soundBoom"			"magic_frost_blast_boom"
				"soundHit"			"magic_frost_blast_hit"
				"aoeTargetDebuff"   "modifier_frost_blast_debuff_datadriven"
				"cp"				"3"
			}
		}

		"Modifiers"
		{
			"modifier_frost_blast_debuff_datadriven"
			{
				"IsDebuff"				"1"
				"EffectName"		"particles/zhuanshen_debuff.vpcf"
				"EffectAttachType"	"follow_chest"
				"Properties"
				{
					"MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE"  "%turn_rate_percent"
					"MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE"	"%speed_percent"
				}
			}
		
		}
    }
}